apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   # important
    userAssignedIdentityID: "<CLIENT-ID>"   # from Terraform

    keyvaultName: "kv-prashant-dev-123"

    objects: |
      array:
        - |
          objectName: my-secret
          objectType: secret